### PR TITLE
KSoft4J 1.1

### PR DESCRIPTION
**Pull request by BenjaminUrquhart**
At this point, the dev branch should be merged into master due to all the changes it has received

### CODE REVIEW

**Comment by mattmalec** [comment]
*unmute when* and yeah, i’ll take a look

**Comment by mattmalec** [comment]
Wait I just forgot, Weather wasn’t documented. Welp idc lmao i’ll do it later or if you wanna

**Comment by BenjaminUrquhart** [comment]
Did you bump the version?

**Comment by mattmalec** [comment]
Not on Bintray or the README

**Pull request merged**
